### ISSUE TITLE
Merges Fail, probably because of Subfolders

### ISSUE THREAD

**Issue by keiex** [bbc-mc/sdweb-merge-board#1]
i'm using subfolders to organize my models and the merge board doesn't seems to work, I've tried only one lane and it still failed

![image](https://user-images.githubusercontent.com/4708589/204243263-04acd52f-55b7-4002-a5ed-17bc167f2e51.png)
![image](https://user-images.githubusercontent.com/4708589/204243386-58dda056-53b3-46a1-be27-003bad1c667c.png)

**Comment by bbc-mc** [comment]
Thank you for reporting!

I found some update about "extra.run_modelmerger" and "Checkpoint format" feature, which affect issue of your report.
And using sub-directory is/has supported on this Extension. (I'm also sub-directory user !)

I found there was change on "extra.run_modelmerger" function now require "checkpoint_format" as new param, and old code dont have.
https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/dac9b6f15de5e675053d9490a20e0457dcd1a23e/modules/extras.py#L253

"checkpoint format" is new functionality, which support new format "safetensors".


So in this commit I do,
- Add error printing code in case exception raises
- Add "Checkpoint format" Radio in UI, default="ckpt"
- "Recipe" format is slightly changed

With this commit, I have no error merging with sub-directory models.

Please try and I hope you enjoy !
