### ISSUE TITLE
error on first run after extension install

### ISSUE THREAD

**Issue by vladmandic** [bbc-mc/sdweb-merge-board#10]
its a simple one - folder `extensions/sdweb-merge-board/csv` is not present on clean install of extension, so writing history file fails  

creating folder manually solves the problem  

i assume the issue is that `git` does not include empty folders in a repository, so when doing a checkout folder is not present  
simply do a `touch csv/.placeholder` so there is a file there and do a commit - or solve it in code with path mkdir if not present   

```text
  File "/home/vlado/dev/automatic/extensions/sdweb-merge-board/scripts/multimerge/util/merge_history.py", line 48, in add_history
    with open(self.filepath, "w", newline="", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/vlado/dev/automatic/extensions/sdweb-merge-board/csv/history.tsv'
```

**Comment by bbc-mc** [comment]
Hi thank you for report.

I had noticed this issue.

and Yes as same as you mentioned above, I 'll add .gitkeep on `extensions/sdweb-merge-board/csv` at next update
(but still I havent yet, no time lol.
