### ISSUE TITLE
[BUG] cant merge anything

### ISSUE THREAD

**Issue by Rogal80** [bbc-mc/sdweb-merge-board#12]
Hi, I always have same issue since a couple of last updates :

Starting merge under settings below,
  A: Base\EpicSpaceMachine.ckpt [4ff93fa8]
  B: Temp\openjourneyAka_v1.ckpt [ddc6edf2]
  C:
  S: Weighted sum
  M: 0.362
  F: False
  O: test
 CF: ckpt
Try to use old 'run_modelmerger' params. 'Checkpoint format is forced to 'ckpt'
<class 'TypeError'>
run_modelmerger() missing 2 required positional arguments: 'checkpoint_format' and 'config_source'
All Multi-Merge process finished. 1 files.
  Error

Windows
Firefox

**Comment by bbc-mc** [comment]
Hi, sorry  to late reply.

I add support for new "run_modelmerger" [at this commit](https://github.com/bbc-mc/sdweb-merge-board/commit/5a5b84eca120667a18c198ec81e63b2d9f14cfa7), so I hope you can merge now.
Please **update Extension** & check it !
