### ISSUE TITLE
New version of gradio breaks everything

### ISSUE THREAD

**Issue by valconius** [bbc-mc/sdweb-merge-board#14]
I'm not sure if this is really gradio's fault, but even by reverting to a week-old commit, merge board seems to fail, and the only next step would presumably be to revert gradio, which is where I gave up investigating this problem.

Your other extension, merge block, does not have the same problem and works perfectly fine.

With gradio 3.16.2, recently updated in webui's requirements file.

The following error results when trying to parse a recipe:
```
Traceback (most recent call last):
  File "/nix/store/b526rlzxv4kldhi97xkp38dz9yz7gb4b-python3.10-gradio-3.16.2/lib/python3.10/site-packages/gradio/routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "/nix/store/b526rlzxv4kldhi97xkp38dz9yz7gb4b-python3.10-gradio-3.16.2/lib/python3.10/site-packages/gradio/blocks.py", line 1018, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/nix/store/b526rlzxv4kldhi97xkp38dz9yz7gb4b-python3.10-gradio-3.16.2/lib/python3.10/site-packages/gradio/blocks.py", line 953, in postprocess_data
    assert isinstance(
AssertionError: <class 'gradio.layouts.Row'> Component with id 2364 not a valid output component
```

The following error results when trying to run a merge:
```
Start Merge processes. Total process num: 1 .
Starting merge under settings below,
  A: sd15.ckpt
  B: sd14.ckpt
  C:
  S: Weighted sum
  M: 0.5
  F: False
  O: helloworld
 CF: ckpt
Try to use old 'run_modelmerger' params. 'config_source' is ignored
Try to use old 'run_modelmerger' params. 'Checkpoint format is forced to 'ckpt'
<class 'TypeError'>
run_modelmerger() missing 4 required positional arguments: 'custom_name', 'checkpoint_format', 'config_source', and 'bake_in_vae'
All Multi-Merge process finished. 1 files.
  Error
```

**Comment by saftle** [comment]
I can confirm the same issue. It's due to the changes they added for regular merges, like the ability to bake in VAEs. I hope this problem can be fixed somehow because this extension would be super handy.

**Comment by bbc-mc** [comment]
Hi, thank you for reporting both of you !

This includes two issues.

First one, `AssertionError: <class 'gradio.layouts.Row'> Component with id 2364 not a valid output component` is related with change of Gradio version.
Now Gradio dont allow to `Row` disapper handy... I'm tucling about work-around this, but still not good idea.

Second one is ,as commented by saftle, caused by AUTO1111's change about `bake in VAEs`.
I will fix it.
