### ISSUE TITLE
Filenames containing plus signs are not parsed correctly in the recipe tab

### ISSUE THREAD

**Issue by Araeos** [bbc-mc/sdweb-merge-board#3]
When selecting files with plus symbols in their name from the multi merge tab everything works as expected, but sending it to the recipe tab results in recipe that will fail to parse correctly, truncating the last terms from the string since it assumes `+` is not part of the file name.
If it is unclear, I can generate an example scenario.

**Comment by bbc-mc** [comment]
Thank you for report.

I update parse logic, please try.


Test for parse logic shown below,

## Test1
- "Send to Recipe" from "Multi-Merge" tab, with A1 = `++++.ckpt` and B1 = `++++++++++.ckpt`,
```
# Recipe TEST 1
mergeA = ++++ + ++++++++++, 0.5  # => success. use " + " as separator
mergeB = ABCD+EFGH, 0.5          # => success, use "+" as separator
```
```
# Parse Result
mergeA = ++++ + ++++++++++,  0.5, ckpt
mergeB = ABCD + EFGH,  0.5, ckpt
```
## Test2
Note: If your want to use checkpoint name includes "+" as part of name, use " + " as connector of checkpoint name, as bellow,
```
# Recipe TEST 2 (to be failed)
mergeC = +++++++++++++++, 0.5    # => failed
# Recipe 
mergeC =  + ,  0.5, ckpt
```
