### ISSUE TITLE
ValueError: not enough values to unpack (expected 87, got 86)  when start webui

### ISSUE THREAD

**Issue by andyleeyuan** [bbc-mc/sdweb-merge-board#5]
After I update the script, go an error when start webui
```
Error executing callback ui_tabs_callback for C:\stable-diffusion-webui\extensions\sdweb-merge-board\scripts\merge_board.py
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\modules\script_callbacks.py", line 95, in ui_tabs_callback
    res += c.callback() or []
  File "C:\stable-diffusion-webui\extensions\sdweb-merge-board\scripts\merge_board.py", line 29, in on_ui_tabs
    btn_run_merge, btn_reload_checkpoints, btn_send_to_recipe, submit_result, btn_clear_merge_settings, \
ValueError: not enough values to unpack (expected 87, got 86)
```

**Comment by bbc-mc** [comment]
Hi,
from your report, `ui_merge.py` code is not loaded correctly.
that is changed in latest update).
`(expected 87, got 86)` means old `ui_merge.py` is still running!

please try either actions below, (I think no.1 enough)

1. **Restart AUTO webui**
- not from "Apply and restart UI" button on webui.
- latest commit includes UI changes, and sometimes this kind of change requires full-restart to load code correctly.

2. **Re-Install extension**
- delete `extensions\sdweb-merge-board`, and re-install.

**Comment by andyleeyuan** [comment]
> 

Thanks,It works!

**Comment by bbc-mc** [comment]
Im grad to hear that, enjoy !
