### ISSUE TITLE
Error loading/saving model file:

### ISSUE THREAD

**Issue by hornedpariah** [bbc-mc/sdweb-merge-board#6]
I installed it through the extension tab of A 1111, my models are in the model folder, some are nested in other folders for organization.
i fill out the merge board and im getting this error:  `Error loading/saving model file:` for each row of the mergeboard i filled.

**Comment by bbc-mc** [comment]
I can't reproduce the error, please show me some step to reproduce that.

Error message "Error loading/saving model file:" raises if model merge function failed.
(not only for loading models)
It's my bad, bad Error message, I'll fix that.

I'm also using subdirectory like below, and meet no error with it,
```
z/test/f99.ckpt
```

**Comment by hornedpariah** [comment]
I tried reproducing this error after giving it  a break and i'm now no longer able to reproduce it. i restarted and everything worked without incident.

**Comment by bbc-mc** [comment]
Thanks for the report.

I understand that the error did not recur.
I'll try to show a few more messages/informations when the error occurs in the next update.

Let me know if it recurs again.
