### ISSUE TITLE
[Question] How to change the directory of result file that merged

### ISSUE THREAD

**Issue by Acise** [bbc-mc/sdweb-merge-board#7]
May I confirm how to change the directory of result file that merged? I want to set results to another folder to ensure materials are separated with results.
Example:
[ckpt file materials folder which auto loaded]:
`[path]:/drive/material files`

[another folder that use to save merged files]:
`[path] /drive/merged files`

**Comment by bbc-mc** [comment]
Merge board uses function of AUTO1111 to do merge/save checkpoints.
Root directory for models is difined on AUTO1111 as `models\Stable-diffusion`.

btw I tried to save merge output file on sub-directry.
First make sub-directory as `test`, and set "Custom Name" or `(O1) Output ckpt Name` as `test/change_directory_test_checkpoint` and run merge.
It works for me.

**Comment by Acise** [comment]
Great, it's working.
I have also tried for redirect to other drives, relative path and absolute path are workable when saving file. Thank you.

_btw, I'm no certain once the result folder has been redirected, [Output(O)] function will be workable or not._
